Add image example
GepardGraphics/gepard-js pull request #10
Opened 2020-10-28 18:44 UTC by kkristof

2020-10-29 11:33 UTC, szledan requested changes

2020-10-29 11:33 UTC, szledan commented on examples/img/img.js
> +while(!surface.hasToQuit()) {}
Missing space: `while (!surface...`

2020-10-29 11:43 UTC, kkristof commented on examples/img/img.js
> +while(!surface.hasToQuit()) {}
Thanks, I've updated the branch

2020-10-29 11:45 UTC, szledan approved these changes
LGTMQI +1

2020-10-30 07:16 UTC, bzsolt approved these changes
LGTM

2020-10-30 07:30 UTC, merged