Add simple sprite animation example
GepardGraphics/gepard-js pull request #8
Opened 2020-10-18 20:54 UTC by kkristof

2020-10-29 11:31 UTC, szledan requested changes

2020-10-29 11:31 UTC, szledan commented on examples/sprite/sprite.js
> +    if ((new Date().getTime() - start) > milliseconds){
missing white-space: `...milliseconds) {...`

2020-10-29 11:31 UTC, szledan commented on examples/sprite/sprite.js
> +for(i = 0; !surface.hasToQuit() && i < 21; i++) {
missing space: `for (i = 0;...`

2020-10-29 11:31 UTC, szledan commented on examples/sprite/sprite.js
> +    if (!(i%5)){
missing spaces: `...(!(i % 5)) {...`

2020-10-29 11:40 UTC, kkristof commented
@szledan Thanks for the review, I've fixed the style issues.

2020-10-29 11:41 UTC, szledan approved these changes
LGTM +1

2020-10-30 07:10 UTC, bzsolt approved these changes
LGTM

2020-10-30 07:31 UTC, merged